version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "toor"
      RABBITMQ_DEFAULT_VHOST: "/"
  
  order_payer:
    build: ./order/
    command: npm run dev
    volumes:
      - ./order:/app/
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    
  api_shop:
    build: ./api_shop/
    command: python manage.py runserver
    volumes:
      - ./api_shop/:/code/
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
    driver: local