version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "toor"
      RABBITMQ_DEFAULT_VHOST: "/"

  api_shop:
    build: ./api_sale/
    command: npm run dev
    volumes:
      - ./api_sale:/app/
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
  
  worker_payer:
    build: ./worker_payer/
    command: npm run dev
    volumes:
      - ./worker_payer:/app/
    restart: "always"
    depends_on:
      - rabbitmq
  
  mongo_api:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /db_mongo:/data/db

volumes:
  rabbitmq_data:
    driver: local